name: check code quality

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version:w ['1.78']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions/setup-rust@v2
        with:
          rust-version: ${{ matrix.rust-version }}

      - name: Install dependencies
        run: cargo build

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=12 --max-line-length=127 --statistics --ignore E722,E501

      - name: Test with pytest
        run: |
          pytest \
            --quiet \
            --timeout=9 \
            --durations=10 \
            --numprocesses=auto \
            --dist=loadfile \
            --cov=core \
            tests
